spring:
  application:
    name: BACKEND
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:imwillingtooo@gmail.com}
    password: ${MAIL_PASSWORD:tvxwzafpvzvetbpt}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ec2-52-78-207-84.ap-northeast-2.compute.amazonaws.com:9092
    consumer:
      group-id: pm-backend
      auto-offset-reset: earliest # Consumer 재시작 시, 과거 데이터 포함해서 처리 (데이터 유실 방지)
    producer:
      acks: all  # ISR(In-Sync Replica) 내 모든 복제본에 데이터가 기록되어야만 성공(commit)
      retries: 3
server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET:myVerySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}       # 15분
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:2592000000} # 30일

verification:
  code-expiration: ${VERIFICATION_CODE_EXPIRATION:60000}          # 1분 (인증코드 만료기간)

logging:
  level:
    backend: DEBUG
    org.springframework.r2dbc: DEBUG