spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/pmDatabase?sslMode=disable
    username: root
    password: password
  data:
    redis:
      host: localhost
      port: 6379
      password:

logging:
  level:
    backend: DEBUG
    org.springframework.r2dbc: DEBUG