spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?sslMode=disable&timezone=Asia/Seoul
    username: postgres
    password: test1234
  data:
    redis:
      host: localhost
      port: 6379
      password:
jwt:
  secret: ${JWT_SECRET:myVerySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}       # 15분
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:2592000000} # 30일

logging:
  level:
    io.r2dbc.postgresql.client.ParameterBinding: TRACE
    io.r2dbc.postgresql: DEBUG
    org.springframework.r2dbc.connection: DEBUG
