spring:
  application:
    name: BACKEND
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1시간
      cache-null-values: false
  cloud:
    function:
      definition: notificationConsumer;notificationDlqConsumer;realTimeConsumer;realTimeDlqConsumer
    stream:
      bindings:
        notificationConsumer-in-0:
          destination: notification-events
          group: main-process-group
          consumer:
            max-attempts: 3
            auto-startup: true
        notificationDlqConsumer-in-0:
          destination: notification-events.dlq
          group: dlq-reprocess-group
          consumer:
            max-attempts: 1
            auto-startup: true
        realTimeConsumer-in-0:
          destination: real-time-events
          group: main-process-group
          consumer:
            max-attempts: 3
            auto-startup: true
        realTimeDlqConsumer-in-0:
          destination: real-time-events.dlq
          group: dlq-reprocess-group
          consumer:
            max-attempts: 1
            auto-startup: true
      kafka:
        binder:
          brokers: ec2-52-78-207-84.ap-northeast-2.compute.amazonaws.com:9092
          producer-properties:
            acks: all # ISR(In-Sync Replica) 내 모든 복제본에 데이터가 기록되어야만 성공(commit)
            retries: 3
            enable.idempotence: true # 중복 전송 방지
          consumer-properties:
            auto.offset.reset: earliest  # Consumer 재시작 시, 과거 데이터 포함해서 처리
            enable.auto.commit: false    # manual commit 사용
            spring.json.value.default.type: backend.domain.event.Event
            spring.json.use.type.headers: false
            key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            spring.json.trusted.packages: "*"
            spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:imwillingtooo@gmail.com}
    password: ${MAIL_PASSWORD:tvxwzafpvzvetbpt}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

verification:
  code-expiration: ${VERIFICATION_CODE_EXPIRATION:60000}          # 1분 (인증코드 만료기간)
ai:
    api:
      base-url: http://ec2-52-78-207-84.ap-northeast-2.compute.amazonaws.com:8001
logging:
  level:
    backend: DEBUG
    org.springframework.r2dbc: DEBUG