spring:
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://database-1.c5e2usce6r1z.ap-northeast-2.rds.amazonaws.com:5432/pmDatabase?sslMode=require}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  data:
    redis:
      host: ${REDIS_HOST:your-prod-redis-host}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:your-redis-password}

jwt:
  secret: ${JWT_SECRET:myVerySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:300000}       # 5분
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:2592000000} # 30일

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:pickles3bucket}
    region: ${AWS_REGION:ap-northeast-2}
    access-key: AKIA2HW3ZTMW7JJ4ARPY
    secret-key: 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
    base-url: https://${aws.s3.bucket}.s3.${aws.s3.region}.amazonaws.com/

logging:
  level:
    backend: INFO
    org.springframework.r2dbc: WARN